name: Next.js

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Next.js dependencies
        run: npm ci

      - name: Add environment configuration
        run: echo '${{ secrets.ENV_PRODUCTION }}' > .env.production

      - name: Build Next.js
        run: npm run build

      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          SOURCE: "."
          TARGET: ${{ secrets.DEPLOY_TARGET }}

      - name: Run deployed code via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_TARGET }}
            pm2 stop --silent chat-app
            pm2 delete --silent chat-app
            pm2 start npm --name "chat-app" -- start
