name: Deploy Next.js to Production

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-push:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add environment configuration
        run: echo '${{ secrets.ENV_PRODUCTION }}' > .env.production

      - name: Log in to Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}
          secrets: |
            "env=${{ secrets.ENV_PRODUCTION }}"

      # - name: Build Next.js
      #   run: npm run build

      # - name: Deploy to Production
      #   uses: easingthemes/ssh-deploy@v2
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      #     REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
      #     REMOTE_USER: ${{ secrets.DEPLOY_USER }}
      #     SOURCE: "."
      #     TARGET: ${{ secrets.DEPLOY_TARGET }}

      - name: Run Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo ${{ env.REGISTRY }}/${{ github.repository }}
            docker stop chat_app || true
            docker rm chat_app || true
            docker run -d --name chat_app -v ${{ secrets.ENV_PRODUCTION_FILE_PATH }}:/usr/src/app/.env.production -p 3000:3000 ${{ env.REGISTRY }}/${{ github.repository }}



# name: Next.js

# on:
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [ 12.x ]

#     steps:
#       - uses: actions/checkout@v2

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install Next.js dependencies
#         run: npm ci

#       - name: Build Next.js
#         run: npm run build
